Brewfile: Removing apple-gcc42
When running the `Brewfile` I run into this issue:

    This formula either does not compile or function as expected on macOS
    versions newer than Mavericks due to an upstream incompatibility.
    Error: An unsatisfied requirement failed this build.

Removing it.